apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-sched
spec:
  completions: 4
  template:
    metadata:
      labels:
        app: pi-test-default
    spec:
      containers:
      # comment below out to use default scheduler
      schedulerName: scheduling-plugin 
      - name: pi-test
        image: localhost:5000/pi:latest
        resources:
          limits:
            cpu: "8"
          requests:
            cpu: "8"
      restartPolicy: Never