apiVersion: v1
kind: Pod
metadata:
  name: test-pi
spec:
  # schedulerName: kubeflux-plugin # comment this out to get it scheduled by the default scheduler
  # schedulerName: scheduling-plugin
  containers:
  - name: test-pi
    # image: gcr.io/google-samples/kubernetes-bootcamp:v1
    # image: pi:latest
    image: localhost:5000/pi:latest
    # image: xuyilindocker/testing:latest
  restartPolicy: Never